Bulletin/urls.py
from django.urls import path

from . import views

app_name = 'Bulletin'

# 页面
pages = [
	path('', views.page_homepage, name='homepage'),
    # path('log/', views.page_log, name='log'),
]

# 接口
apis = [
	# path('api/log/add/', views.api_add_log, name='api_add_log'),
    # path('api/preference/update/', views.api_preference_update, name='api_preference_update')
]

urlpatterns = pages + apis

CoyaCoffee/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from Main.page.Main import register

djangoURLs = [
    # admin后台
    path('admin/', admin.site.urls),
    # 用户模板
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/create', register, name='register'),
]
    
publicAPPs = [
    path('', include('Main.urls')),
    path('qqgroup/', include('QQGroup.urls')),
    path('bulletin/', include('Bulletin.urls')),
    path('faq/', include('FAQ.urls')),
    path('dashboard/', include('Dashboard.urls')),
    path('tool/fapmaster/', include('FapMaster.urls')),
]

privateAPPs = [

]

urlpatterns = djangoURLs + publicAPPs + privateAPPs

# 开发时可显示用户文件
if settings.DEBUG:
    urlpatterns += [
        re_path(r'^userfile/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

Dashboard/urls.py
from django.urls import path

from . import views

app_name = 'Dashboard'

# 页面
pages = [
	path('<str:user_name>/', views.page_homepage, name='homepage'),
]

# 接口
apis = [
	path('profile/update', views.api_profile_update, name='api_profile_update'),
]

urlpatterns = pages
urlpatterns += apis

FAQ/urls.py
from django.urls import path

from . import views

app_name = 'FAQ'

# 页面
pages = [
	path('', views.page_homepage, name='homepage'),
    # path('log/', views.page_log, name='log'),
]

# 接口
apis = [
	# path('api/log/add/', views.api_add_log, name='api_add_log'),
    # path('api/preference/update/', views.api_preference_update, name='api_preference_update')
]

urlpatterns = pages + apis

FapMaster/urls.py
from django.urls import path

from . import views

app_name = 'FapMaster'

# 页面
pages = [
	path('', views.page_homepage, name='homepage'),
    path('log/', views.page_log, name='log'),
]

# 接口
apis = [
	path('api/log/add/', views.api_add_log, name='api_add_log'),
    path('api/preference/update/', views.api_preference_update, name='api_preference_update')
]

urlpatterns = pages + apis

Main/urls.py
from django.urls import path

from . import views

app_name = 'Main'

# 页面
pages = [
	path('', views.page_homepage, name='homepage'),
]

# 接口
# apis = [
# 	path('api_index/', views.api_index, name=''),
# ]

urlpatterns = pages

QQGroup/urls.py
from django.urls import path

from . import views

app_name = 'QQGroup'

# 页面
pages = [
	path('', views.page_homepage, name='homepage'),
    # path('log/', views.page_log, name='log'),
]

# 接口
apis = [
	# path('api/log/add/', views.api_add_log, name='api_add_log'),
    # path('api/preference/update/', views.api_preference_update, name='api_preference_update')
]

urlpatterns = pages + apis

AFDPatron/models.py
from django.db import models

# Create your models here.

Bulletin/models.py
from django.db import models

Dashboard/models.py
from django.db import models
from django.contrib.auth import settings

from Main.api.file_path_converter import user_img_path

class BaseInfo(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='所属用户')
    sex_choices = (
        ('M', '男'),
        ('F', '女'),
        ('B', '小男孩'),
        ('G', '小女孩'),
        ('H', '武装直升机'),
        ('C', '沃尔玛购物袋'),
        ('R', 'RR的狗'),
        ('S', '不公开'),
    )
    sex = models.CharField(default='S', max_length=1, choices=sex_choices, verbose_name='性别')
    biography = models.CharField(null=True, blank=True,max_length=200, verbose_name='个签')
    avator = models.ImageField(null=True, blank=True, upload_to=user_img_path, verbose_name='头像')

FAQ/models.py
from django.db import models

FapMaster/models.py
from django.db import models
from django.contrib.auth import settings

class FapLog(models.Model):
    """The records of masturbation

    # Fields
    id: auto increase
    user: the one record belongs to
    start_time: auto calculated by end_time and duration
    end_time: defalt datetime.now (fetch in frontend, since you might rest for a while before you record your job)
    duration: timedelta type
    comments: max length 200
    """
    id = models.AutoField(primary_key=True, verbose_name='记录id')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='所属用户')
    start_time = models.DateTimeField(null=True, blank=True, verbose_name='开始时间')
    end_time = models.DateTimeField(verbose_name='结束时间')
    duration = models.DurationField(null=True, blank=True, verbose_name='持续时间')
    comments = models.CharField(null=True, blank=True, max_length=200, verbose_name='备注')

class Preference(models.Model):
    # TODO: 补一下注释
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='所属用户')
    publicize_log = models.BooleanField(default=False, verbose_name='公开FapMaster记录')

LifeBook/models.py
from django.db import models

# Create your models here.

Main/models.py
from django.db import models

# Create your models here.

QQGroup/models.py
from django.db import models

Dashboard/forms/profile.py
from django import forms

class Profile(forms.Form):
    nickname = forms.CharField(max_length=10, required=False, label="昵称")
    email = forms.EmailField(required=False, label="邮箱")
    sex_choices = (
        ('M', '男'),
        ('F', '女'),
        ('B', '小男孩'),
        ('G', '小女孩'),
        ('H', '武装直升机'),
        ('C', '沃尔玛购物袋'),
        ('R', 'RockyRoo的小狗狗'),
        ('S', '不公开'),
    )
    sex = forms.ChoiceField(required=True, choices=sex_choices, initial='S', label="性别")
    biography = forms.CharField(max_length=50, required=False, label="个人签名")
    avator = forms.ImageField(required=False, label="头像")

FapMaster/forms/preferences.py
from django import forms

class FapMaster(forms.Form):
    publicize_log = forms.BooleanField(required=False)  

AFDPatron/views.py
from django.shortcuts import render

# Create your views here.

Bulletin/views.py
from Bulletin.page.homepage import homepage
# from FapMaster.page.log import log

# from FapMaster.api.log import add_log
# from FapMaster.api.preference import update

# # 页面
def page_homepage(request): return homepage(request)
# def page_log(request): return log(request)

# # 接口
# def api_add_log(request): return add_log(request)
# def api_preference_update(request): return update(request)

Dashboard/views.py
from Dashboard.page.homepage import homepage
from Dashboard.api.profile import update
from django.http.response import HttpResponse

# 页面
def page_public(request): return HttpResponse("dashboard public")
def page_homepage(request, user_name): return homepage(request, user_name)

# 接口
def api_profile_update(request): return update(request)

FAQ/views.py
from FAQ.page.homepage import homepage
# from FapMaster.page.log import log

# from FapMaster.api.log import add_log
# from FapMaster.api.preference import update

# # 页面
def page_homepage(request): return homepage(request)
# def page_log(request): return log(request)

# # 接口
# def api_add_log(request): return add_log(request)
# def api_preference_update(request): return update(request)

FapMaster/views.py
from FapMaster.page.homepage import homepage
from FapMaster.page.log import log

from FapMaster.api.log import add_log
from FapMaster.api.preference import update

# 页面
def page_homepage(request): return homepage(request)
def page_log(request): return log(request)

# 接口
def api_add_log(request): return add_log(request)
def api_preference_update(request): return update(request)

LifeBook/views.py
from django.shortcuts import render

# Create your views here.

Main/views.py
from Main.page.Main import homepage

def page_homepage(request): return homepage(request)

QQGroup/views.py
from QQGroup.page.homepage import homepage
# from FapMaster.page.log import log

# from FapMaster.api.log import add_log
# from FapMaster.api.preference import update

# # 页面
def page_homepage(request): return homepage(request)
# def page_log(request): return log(request)

# # 接口
# def api_add_log(request): return add_log(request)
# def api_preference_update(request): return update(request)

Dashboard/templates/Dashboard/base.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
个人空间
{% block title_Dashboard %}{% endblock title_Dashboard %}
{% endblock title %}

{% block css %}
{% block css_Dashboard %}{% endblock css_Dashboard %}
{% endblock css %}

{% block content %}
{% block content_Dashboard %}{% endblock content_Dashboard %}
{% endblock content %}

{% block js %}
{% block js_Dashboard %}{% endblock js_Dashboard %}
{% endblock js %}

Dashboard/templates/Dashboard/homepage/header.html
<ul class="nav nav-tabs sticky-top mt-3" id="nav_tabs" style="z-index: 999;">
  <li class="nav-item">
    <button class="nav-link text-light active" id="nav_homepage" data-bs-toggle="tab" data-bs-target="#tab_homepage" type="button">主页</button>
  </li>
  {% if is_host %}
    <li class="nav-item">
      <button class="nav-link text-light" id="nav_settings" data-bs-toggle="tab" data-bs-target="#tab_settings" type="button">设置</button>
    </li>
  {% endif %}
  <li class="nav-item">
    <button class="nav-link text-light" id="nav_else" data-bs-toggle="tab" data-bs-target="#tab_else" type="button">开发中...</button>
  </li>
</ul>

Dashboard/templates/Dashboard/homepage/homepage.html
{% extends 'Dashboard/base.html' %}

{% load static %}

{% block css_Dashboard %}
  <link rel="stylesheet" href="{% static 'FapMaster/css/homepage/homepage.css' %}" />
  <link href="{% static 'github_contribution/github_contribution_graph.css' %}" media="all" rel="stylesheet" />
{% endblock %}

{% block content_Dashboard %}
  {% include 'header.html' %}
  <div class="container px-5">
    <div class="row">
      <div class="col-12 col-xl-3 mt-3 rounded shadow">
        <div class="row" style="background-color: rgba(255, 255, 255, 0.2);">
          {% include 'Dashboard/homepage/profile/profile.html' %}
        </div>
      </div>
      <div class="col-12 col-xl-9 pt-1 px-1 px-xl-3">
        <div class="mt-3 ms-xl-3 text-light rounded shadow" style="background-color: rgba(255, 255, 255, 0.2);">
          {% include "Dashboard/homepage/header.html" %}
          <div class="tab-content">
            {% include "Dashboard/tabpage/tabpage.html" %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block js_Dashboard %}
  {% if fap_records %}
    <script>
        let fap_records = [
        {% for record in fap_records %}
        {
            timestamp: {{record.timestamp}},
            count: 1
        },
        {% endfor %}];
    </script>
    <script src="{% static 'github_contribution/github_contribution.js' %}"></script>
    <script src="{% static 'FapMaster/js/homepage/records.js' %}"></script>
  {% endif %}
  <script>
    let api_profile_update = "{% url 'Dashboard:api_profile_update' %}"
    let api_FapMaster_preference_update = '{% url "FapMaster:api_preference_update" %}'
  </script>
  <script src="{% static 'Dashboard/js/homepage/profile.js' %}"></script>
{% endblock %}

Dashboard/templates/Dashboard/homepage/profile/modal_edit_profile.html
<div class="modal fade" id="modal_edit_profile" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-primary">个人资料</h5>
        <button type="button" class="close" data-bs-dismiss="modal"><span>×</span></button>
      </div>
      <div class="modal-body text-dark">
        <form id="form_edit_profile" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{form_profile}}
      </div>
      <div class="modal-footer">
        <button type="submit" form="form_edit_profile" class="btn btn-primary">保存</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">关闭</button>
      </div>
    </div>
  </div>
</div>

Dashboard/templates/Dashboard/homepage/profile/profile.html
{% load static %}
<div class="col-6 col-xl-12 position-relative text-center py-3 pt-xl-4 px-xl-5">
  <img class="img-fluid rounded-circle shadow-lg"
    src="{% if host.base_info.avator %}
      {{ MEDIA_URL }}{{ host.base_info.avator }}
    {% else %}
      {% static 'Dashboard/img/default_avator.png' %}
    {% endif %}" />
</div>
<div class="col-6 col-xl-12 my-3 mt-xl-3 ps-3 fs-xl-5">
  <div class="mb-2">
    <strong>昵称：</strong>
    <br class="d-inline d-sm-none" />
    {{host.first_name}}
  </div>
  <div class="mb-2">
    <strong>用户名：</strong>
    <br class="d-inline d-sm-none" />
    {{ host.username }}
  </div>
  <div class="mb-2">
    <strong>性别：</strong>
    <br class="d-inline d-sm-none" />
    {{ host.base_info.get_sex_display }}
  </div>
</div>
<div class="col-12 ps-3 d-inline">
  <strong>邮箱：</strong>
  <br class="d-inline d-sm-none" />
  <a href="mailto:{{ host.email }}">{{ host.email }}</a>
</div>
<div class="col-12 ps-3 mt-1 d-inline">
  <strong>个人签名：</strong>
  <br class="d-inline d-sm-none" />
  {% if host.base_info.biography %}
    {{ host.base_info.biography }}
  {% else %}
    无
  {% endif %}
</div>

{% if is_host %}
  <div class="text-end my-2">
    <a href="#" data-bs-toggle="modal" data-bs-target="#modal_edit_profile" class="btn btn-primary">编辑</a>
  </div>
  {% include "Dashboard/homepage/profile/modal_edit_profile.html" %}
{% endif %}

Dashboard/templates/Dashboard/tabpage/homepage.html
{% if fap_records %}
    <h2>手工记录</h2>
    <div class="col-12 mt-1 mt-xl-3">
        {% include "FapMaster/records.html" with show_all=False %}
    </div>
{% endif %}

Dashboard/templates/Dashboard/tabpage/tabpage.html
<div class="tab-pane pt-3 show active" id="tab_homepage">
  {% include 'Dashboard/tabpage/homepage.html' %}
</div>
{% if is_host %}
  <div class="tab-pane pt-3" id="tab_settings">
    {% include 'Dashboard/tabpage/settings/settings.html' %}
  </div>
{% endif %}
<div class="tab-pane pt-3" id="tab_else">开发中...</div>

FapMaster/templates/FapMaster/base.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
撸大湿
{% block title_FapMaster %}{% endblock title_FapMaster %}
{% endblock title %}

{% block css %}
{% block css_FapMaster %}{% endblock css_FapMaster %}
{% endblock css %}

{% block content %}
{% block content_FapMaster %}{% endblock content_FapMaster %}
{% endblock content %}

{% block js %}
{% block js_FapMaster %}{% endblock js_FapMaster %}
{% endblock js %}

FapMaster/templates/FapMaster/fap.html
<div class="mt-1 text-center">
  {% include 'FapMaster/homepage/timeline/control/control.html' %}
</div>

FapMaster/templates/FapMaster/homepage/homepage.html
{% extends 'FapMaster/base.html' %}

{% load static %}

{% block css_FapMaster %}
  <link rel="stylesheet" href="{% static 'FapMaster/css/homepage/homepage.css' %}" />
  <link href="{% static 'github_contribution/github_contribution_graph.css' %}" media="all" rel="stylesheet" />
{% endblock %}

{% block content_FapMaster %}
  {% include 'header.html' %}
  <div class="container px-4">
    <div class="row">
      <div class="col-xxl-3 col-xl-2 col-lg-2 pt-3 d-none d-lg-block d-xl-block d-xxl-block">
        {% include 'FapMaster/homepage/panel/panel.html' %}
      </div>
      <div class="col-xxl-9 col-xl-10 col-lg-10 col-12 pt-3">
        {% include 'FapMaster/homepage/timeline/timeline.html' %}
      </div>
    </div>
  </div>
{% endblock %}

{% block js_FapMaster %}
  <script>
  let api_add_log = '{% url "FapMaster:api_add_log" %}';
  let fap_records = [
  {% for log in my_logs %}
    {
      timestamp: {{log.timestamp}},
      count: 1
    },
  {% endfor %}];
</script>
  <script src="{% static 'github_contribution/github_contribution.js' %}"></script>
  <script src="{% static 'FapMaster/js/log/log.js' %}"></script>
  <script src="{% static 'FapMaster/js/homepage/control.js' %}"></script>
  <script src="{% static 'FapMaster/js/homepage/homepage.js' %}"></script>
  <script src="{% static 'FapMaster/js/homepage/records.js' %}"></script>
  <script src="{% static 'FapMaster/js/panel/preference.js' %}"></script>
  <script>
    let api_FapMaster_preference_update = '{% url "FapMaster:api_preference_update" %}'
  </script>
{% endblock %}

FapMaster/templates/FapMaster/homepage/timeline/timeline.html
{% if user.is_authenticated %}
<div class="fs-3">
  <span class="fw-bold">{{ user.first_name }}</span>
  <span class="text-secondary">@{{ user.username }}</span>
</div>
{% endif %}
{% if my_logs %}
  {% include 'FapMaster/records.html' %}
  <div class="row text-end">
    <a href="{% url 'FapMaster:log' %}"><span class="text-light">全部记录 >>></span></a>
  </div>
{% endif %}
{% if user.is_authenticated %}
{% include "FapMaster/fap.html" %}
<hr />
{% endif %}
<div class="fs-3 fw-bold">排行</div>
{% include "FapMaster/homepage/rank/rank.html" %}

<div class="fs-3 fw-bold">探索</div>

<ol class="list-group list-group-numbered list-group-flush mt-3">
  {% for log in logs %}
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <a href="{% url "Dashboard:homepage" log.user.username %}">
          <span class="fw-bold">{{ log.user.first_name }}</span>
          <span class="text-light">@{{ log.user.username }}</span>
        </a>
        <div class="text-light">
          {% if log.comments %}
            {{ log.comments }}
          {% else %}
            无备注
          {% endif %}
        </div>
      </div>
      <span class="me-4 text-light">{{ log.end_time|timesince }} 前</span>
      <span class="text-info bi bi-hand-thumbs-up me-2"></span>
      <span class="text-info me-3">0</span>
      <span class="text-info bi bi-chat-right-text me-2"></span>
      <span class="text-info">0</span>
    </li>
  {% endfor %}
</ol>

FapMaster/templates/FapMaster/records.html
<div id="records" class="row ps-0 text-light rounded"></div>

Main/templates/Main/base.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% block title_Main %}{% endblock title_Main %}
{% endblock title %}

{% block css %}
{% block css_Main %}{% endblock css_Main %}
{% endblock css %}

{% block content %}
<div>
    {% block content_Main %}{% endblock content_Main %}
</div>
{% endblock content %}

{% block js %}
{% block js_Main %}{% endblock js_Main %}
{% endblock js %}

Main/templates/Main/homepage/apps.html
{% load static %}
<div class="row">
  <div class="row">
    <h2>交流</h2>
    <div class="col-3">
      <a href="{% url 'QQGroup:homepage' %}">
        <img src="{% static 'QQGroup/img/QQgroup.png' %}" class="card-img-top img-fluid border border-2 rounded-5" alt="喵喵屋" />
        <div class="text-center mt-2 text-light">
          <small>喵喵屋</small><br><small>粉丝群</small>
        </div>
      </a>
    </div>
    <div class="col-3">
      <a href="{% url 'FAQ:homepage' %}" class="disabled">
        <img src="{% static 'FAQ/img/icon.jpeg' %}" class="card-img-top img-fluid border border-2 rounded-5" alt="匿名问答" />
        <div class="text-center mt-2 text-light">
          <small>匿名问答</small>
        </div>
      </a>
    </div>
  </div>
  <hr>
  <div class="row">
    <h2>工具</h2>
    <div class="col-3">
      <a href="{% url 'FapMaster:homepage' %}">
        <img src="{% static 'FapMaster/img/icon.jpg' %}" class="card-img-top img-fluid border border-2 rounded-5" alt="撸大湿" />
        <div class="text-center mt-2 text-light">
          <small>撸大湿</small>
        </div>
      </a>
    </div>
  </div>
  <hr>
  <div class="row">
    <h2>其他</h2>
    <div class="col-3">
      <a href="{% url 'Bulletin:homepage' %}">
        <img src="{% static 'Bulletin/img/icon.png' %}" class="card-img-top img-fluid border border-2 rounded-5" alt="站点公告" />
        <div class="text-center mt-2 text-light">
          <small>站点公告</small>
        </div>
      </a>
    </div>
  </div>
  <hr>
</div>

Main/templates/Main/homepage/beian.html
<div class="fixed-bottom border-top text-center bg-light">
    <div class="text-secondary">
        <small>版本：v0.1 【dev】</small>
        <small class="ms-3">
            备案号：<a href="https://beian.miit.gov.cn/">渝ICP备19014188号-1</a>
        </small>
    </div>
</div>

Main/templates/Main/homepage/blog.html
<div style="height: 100vh;">
  <div class="text-center border border-primary border-opacity-50">
    <span class="text-secondary fs-5">【开发中的区块】前面的区域以后再来探索吧</span>
  </div>
</div>

Main/templates/Main/homepage/description.html
<h2>简介</h2>
<p>你好，欢迎光临<a href="#">拾心咖啡屋</a>！这里是由<a href="https://space.bilibili.com/39012132">RockyRoo</a>与<a href="https://space.bilibili.com/10936501">哲予</a>共同开发、维护的对外开放站点。</p>
<p>这里提供与我们相关的信息与工具，包括但不限于各平台链接、粉丝群相关、游戏服务器等。</p>

Main/templates/Main/homepage/homepage.html
{% extends 'Main/base.html' %}
{% load static %}

{% block title_Main %}
  主页
{% endblock %}

{% block css_Main %}
{% endblock css_Main %}

{% block content_Main %}
  {% include 'header.html' %}
  <div class="container">
    <div class="pt-2 px-3">
      <div>
        <div class="row mt-3" style="z-index: 1;">
          {% include 'Main/homepage/description.html' %}
          <hr />
        </div>
        <div class="row">
          <div class="col-12 col-xl-7 pt-3">
            {% include 'Main/homepage/apps.html' %}
          </div>
          <div class="col-12 col-xl-5 pt-3">
            {% include 'Main/homepage/update.html' %}
          </div>
        </div>
        <div class="row mt-3">
          {% include 'Main/homepage/blog.html' %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

Main/templates/Main/homepage/update.html
<h2>主站公告</h2>
{{update|safe}}

QQGroup/templates/QQGroup/homepage/homepage.html
{% extends 'QQGroup/base.html' %}

{% load static %}

{% block css_QQGroup %}
{% endblock %}

{% block content_QQGroup %}
  {% include 'header.html' %}
  <div class="container px-5 pt-3">
    <div class="row">
        {{html|safe}}
    </div>
  </div>
{% endblock %}

{% block js_QQGroup %}
{% endblock %}